# -*- coding: utf-8 -*-
"""CoveTest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TeY3u8P1hqoQr_v92I4YIi2GokYqzb0E
"""

!nvidia-smi

# Commented out IPython magic to ensure Python compatibility.
# %cd ./drive/My Drive/PyTorch

# !git clone https://github.com/salesforce/cove.git

!ls

# Commented out IPython magic to ensure Python compatibility.
# %cd ./cove

!ls

# 安装所需软件包

!pip install -r ./requirements.txt

# 安装CoVe

!python setup.py develop

import torch
from torchtext.vocab import GloVe
from cove import MTLSTM

# GloVe词表，维度为2.1*10^6*3

glove = GloVe(name='840B', dim=300, cache='.embeddings')

# 输入2个句子，每个句子中每个单词在词表中的编号

inputs = torch.LongTensor([[10, 2, 3, 0], [7, 8, 10, 3]]);inputs

# 两个句子的长度分别为3和4

lengths = torch.LongTensor([3, 4]);lengths

# CoVe类

cove = MTLSTM(n_vocab=glove.vectors.shape[0], vectors=glove.vectors, model_cache='.embeddings')

# 每个句子每个单词的CoVe编码，维度为2*4*600

outputs = cove(inputs, lengths);outputs

outputs.shape

